### ISSUE TITLE
Error : export 'NgxSimpleIconsComponent' was not found in 'ngx-simple-icons'

### ISSUE THREAD

**Issue by PolSpock** [avmaisak/ngx-simple-icons#7]
Hello,

I'm trying to use `ngx-simple-icons` for angular but i'm not able to launch a project without error :(
Here my errors :

```
./src/app/app.component.ts:11:22-48 - Error: export 'NgxSimpleIconsComponent' (imported as 'i1') was not found in 'ngx-simple-icons' (module has no exports)

./src/app/app.module.ts:12:12-37 - Error: export 'NgxSimpleIconsModule' (imported as 'NgxSimpleIconsModule') was not found in 'ngx-simple-icons' (module has no exports)

./src/app/app.module.ts:12:40-50 - Error: export 'activision' (imported as 'activision') was not found in 'ngx-simple-icons' (module has no exports)

./src/app/app.module.ts:12:52-59 - Error: export 'adobexd' (imported as 'adobexd') was not found in 'ngx-simple-icons' (module has no exports)

./src/app/app.module.ts:14:156-179 - Error: export 'NgxSimpleIconsModule' (imported as 'i1') was not found in 'ngx-simple-icons' (module has no exports)

```

**See my demarch to reproduce the error :**

First of all, my angular version :
```
ng --version

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/


Angular CLI: 13.2.5
Node: 16.13.2
Package Manager: npm 8.1.2
OS: win32 x64

Angular: 13.2.4
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1302.5
@angular-devkit/build-angular   13.2.5
@angular-devkit/core            13.2.5
@angular-devkit/schematics      13.2.5
@angular/cli                    13.2.5
@schematics/angular             13.2.5
rxjs                            7.5.4
typescript                      4.5.5

```

1) Create a clear and new angular project this `ng new mytestproject`

2) Like [README.MD](https://github.com/avmaisak/ngx-simple-icons#readme) asking, install the package with : `npm i ngx-simple-icons --save`

3) Then in app.module.ts file, add :
```
import { 
  NgxSimpleIconsModule, 
  activision,
  adobexd,
} from 'ngx-simple-icons';
```
and 
`NgxSimpleIconsModule.pick({ activision, adobexd })
`

So the `app.module.ts` look like this :
```
import { NgModule } from '@angular/core';
import { BrowserModule } from '@angular/platform-browser';
import { 
  NgxSimpleIconsModule, 
  activision,
  adobexd,
} from 'ngx-simple-icons';
import { AppComponent } from './app.component';

@NgModule({
  declarations: [
    AppComponent
  ],
  imports: [
    BrowserModule,
    NgxSimpleIconsModule.pick({ activision, adobexd })
  ],
  providers: [],
  bootstrap: [AppComponent]
})
export class AppModule { }
```

4) Finally try to start your project (with `npm start` for example) and you will get the same error as me

Can you help me ? I've missed something ?

Regards

**Comment by avmaisak** [comment]
@PolSpock thank you for issue. Just wait few moments, i will see what's the problem

**Comment by pekempy** [comment]
@avmaisak I've got the same error in that my app.module.ts can't load the module.
`./src/app/app.module.ts:46:8-28 - Error: export 'NgxSimpleIconsModule' (imported as 'NgxSimpleIconsModule') was not found in 'ngx-simple-icons' (module has no exports)`

Do you have any update on this?

**Comment by pekempy** [comment]
I have the same issue. 
I also noticed the following:

`public-api.d.ts` had an error on `export * from './lib/types';` which I fixed by changing ./lib/types to code from this repo rather than what npm installed 

First line being:
```export type IconName = 'icon_1001tracklists' |```

instead of 
```export declare type IconName = ```

I'm guessing the module needs updating

I'm still getting the ```Error: export 'NgxSimpleIconsModule' (imported as 'NgxSimpleIconsModule') was not found in 'ngx-simple-icons' (module has no exports)``` though

**Comment by avmaisak** [comment]
@PolSpock , @pekempy . Guys. I will fix it as soon as possible.

**Comment by avmaisak** [comment]
@PolSpock , @pekempy. Sorry for long answer. The problem, probably, has been fixed, PLease, checkout latest version!

**Comment by avmaisak** [comment]
demo project updated and works fine.
https://github.com/avmaisak/ngx-simple-icons/tree/develop/ngx-simple-icons-demo/src

**Comment by PolSpock** [comment]
It work ! Thanks :)
